apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# The resources to be scraped are versioned without the labels that Prometheus Operator matches on
# so the purpose of this kustomize base is to collect them and set a chosen label
commonLabels:
  prometheus: now

resources:
- ../k8s
- ../node-exporter
- ../kube-state-metrics
- ../kubernetes-mixin
- ../assertions_failed
- ../scrape-annotations
- github.com/solsson/prometheus-operator/example/applyable-alerts/?ref=55ce571ef95b90d46257e469aa5d1885594fd4c1
