apiVersion: skaffold/v2beta4
kind: Config
metadata:
  name: assert-runtime-nodejs
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert/runtime-nodejs
    context: ./
    custom:
      buildCommand: y-build
      dependencies:
        dockerfile:
          path: Dockerfile
    sync: # This is where we should look if we want to include env vars?
      manual:
      # With skaffold dev this is the runtime's specs, which is why it differs from the COPY directive in the Dockerfile
      - src: 'specs/**'
        dest: /usr/src
test:
- image: builds-registry.ystack.svc.cluster.local/yolean/kubernetes-assert/runtime-nodejs
  structureTests:
  - './structure-test/*'
deploy:
  kustomize:
    paths:
    - dev-ystack
