#!/bin/bash
set -e

[ -z "$IMAGE_NAME" ] && echo "IMAGE_NAME is required" && exit 1;

function imagename {
  buildname=$1
  case $IMAGE_NAME in
    *:latest) echo -n $IMAGE_NAME | sed "s|:latest|:$buildname|" ;;
    *:*) echo -n $IMAGE_NAME | sed "s|:\(.*\)|:\1-$buildname|" ;;
    *) echo $IMAGE_NAME:$buildname ;;
  esac
}

docker build -t $IMAGE_NAME .

CONTEXTS="
runtime-nodejs
specs
"

PUSH=""

for CONTEXT in $CONTEXTS; do

  CONTEXT_IMAGE_NAME=$(imagename $CONTEXT)

  docker build -t $CONTEXT_IMAGE_NAME -t yolean/assert-$CONTEXT:$SOURCE_COMMIT ./$CONTEXT
  PUSH="$PUSH $CONTEXT_IMAGE_NAME yolean/assert-$CONTEXT:$SOURCE_COMMIT"

done

echo "PUSH list contains: $PUSH"
[ -z "$NOPUSH" ] || exit 0
for P in $PUSH; do docker push $P; done
