apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- scrapeable-deployment.yaml
# TODO if many tests reuse this base, how do we manage podmonitor?
#- kustomize/scrapeable-podmonitor.yaml
