apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: assert-specs
build:
  tagPolicy:
    gitCommit:
      variant: CommitSha
  artifacts:
  - image: builds-registry.ystack.svc.cluster.local/yolean/assert-specs
    context: ./
    custom:
      buildCommand: >-
        y-build-like-sync
        builds-registry.ystack.svc.cluster.local/yolean/assert-runtime-nodejs:../../kubernetes-assert/runtime-nodejs
    sync:
      manual:
      - src: '**'
        dest: /usr/src/specs
  cluster: {}
deploy:
  kustomize: {}
