apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
- ../rbac-prometheus
- ../base-label-prometheus-now
# Needs separate kubectl replace -k
#- ../kubernetes-mixin-dashboards
- main-alertmanager-service.yaml
- main-alertmanager.yaml
- now-prometheus-service.yaml
- now-prometheus.yaml

generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: alertmanager-main
  files:
  - alertmanager.yaml
