namespace: monitoring
bases:
- ../prometheus-operator
- ../rbac-prometheus
- ../base-label-prometheus-now
# Needs separate kubectl replace -k
#- ../kubernetes-mixin-dashboards
resources:
- main-alertmanager-service.yaml
- main-alertmanager.yaml
- now-prometheus-service.yaml
- now-prometheus.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
- name: alertmanager-main
  files:
  - alertmanager.yaml
